### ISSUE TITLE
Pacman install issue with riscv64 package

### ISSUE THREAD

**Issue by Krys600** [thefossguy/archlinux-visionfive2#8]
Hello,

when i try to run the ./create-image.sh script with root privilege, l’m facing with this error when pacman is trying to install the requirement package : 

error: failed to prepare transaction (package architecture is not valid)
:: package linux-starfive-visionfive2-5.15.0.arch1-3-riscv64 does not have a valid architecture
:: package linux-starfive-visionfive2-headers-5.15.0.arch1-3-riscv64 does not have a valid architecture

Should i change some settings from pacman to allow install those package ?

I'm using a pure Arch Linux distro X86_64

Thx

**Comment by thefossguy** [comment]
> I'm using a pure Arch Linux distro X86_64

This script is meant to be run on a RISC-V machine, natively. You can try QEMU to build an image but I haven't used that because I already have a VF2 to build such things on.

**Comment by ankurkotwal** [comment]
I'm wondering if we should add an architecture check in the script. I'll try and get a PR for that soon.

**Comment by thefossguy** [comment]
Handled in c12cbea600ec43c08eb02982bc40dbef5ccecc06
Thanks for the reminder Ankur! I had forgotten to add this check.
